name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
autolabeler:
  - label: 'bug'
    branch:
      - '/fix/i'
    title:
      - '/fix/i'
  - label: 'jira'
    branch:
      - '/aa-[0-9]{1,4}/i'
    title:
      - '/aa-[0-9]{1,4}/i'
categories:
  - title: '🚀 Jira'
    labels:
      - 'jira'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
version-template: "$MAJOR.$MINOR"
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  default: minor
template: |
  ## Changes
  
  $CHANGES
