name: Release Deployment

on:
  release:
    types: [ published ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  post_to_netlify_buildhook:
    runs-on: ubuntu-latest
    steps:
      - name: POST to Build Hook
        run: curl -X POST -d {} ${{secrets.NETLIFY_BUILD_HOOK}}?trigger_branch=main&trigger_title=Release+${{env.GITHUB_REF}}
